### ISSUE TITLE
command line option to exclude files

### ISSUE THREAD

**Issue by jmborr** [johann-petrak/licenseheaders#25]
Add a command line option that will read in one or more UNIX-style patterns. Any file name matching this pattern will be ignored. No license will be incorporated.
```
licenseheaders ... -x "_version.py,*not_this_one*"
```

**Comment by cocoa-maemae** [comment]
Hello. Was the function mentioned aforementioned implemented in addition finally?
Thanks

**Comment by jmborr** [comment]
No, I forked the repository and that's why I closed the issue. I'll try to implement that functionality in the forked repo and then open a PR to your repo. The biggest hurdle is finding time, as usual 😄

**Comment by rcaroncd** [comment]
Done
https://github.com/johann-petrak/licenseheaders/pull/35

**Comment by johann-petrak** [comment]
Thanks, I have merged the PR, but I am going to leave this open since it only checks for literal matches, not REs or globs.

**Comment by johann-petrak** [comment]
OK, it should be possible now to add glob patterns, e.g. `-x 'somedir/*' '*.ext'` to ignore files in the directory `somedir` and ignore all files with extension `ext` 

More testing required.

**Comment by johann-petrak** [comment]
Seems to work.
