### ISSUE TITLE
Push version 0.8 to PyPI (to make additional-extensions available)

### ISSUE THREAD

**Issue by lschmelzeisen** [johann-petrak/licenseheaders#30]
Hi! The master branch added the very useful feature `--additional-extensions` (in pull request #23). However, that feature has not yet made it's way to a published version on PyPI. Is there anything that prevents pushing out a new version 0.8 with that feature?

**Comment by johann-petrak** [comment]
Was working on another change, adding option -E
Version 0.8 should no be available on pypi.
Thanks!

**Comment by johann-petrak** [comment]
Please use version 0.8.1, forgot to commit a change before pushing 0.8
