### ISSUE TITLE
Remove import in .Java files.

### ISSUE THREAD

**Issue by lbize** [johann-petrak/licenseheaders#31]
Hello.
Just use the last release v0.5. Works perfectly to add a license header but remove imports, and static imports.

**Comment by johann-petrak** [comment]
I am not sure I understand the issue you report.
The last/current version is 0.8.1, see https://pypi.org/project/licenseheaders/
If the problem occurs with that version, could you please provide a file where it happens?
Thank you.

**Comment by lbize** [comment]
Would you excuse me. I was unclear.
I used the last release in github release (v0.5) after a git clone. As you suggest, i'm going to test from pip install and not directly from the last github tag. Sorry

**Comment by johann-petrak** [comment]
Oh I totally forgot about the github releases, I stopped creating them once I moved to Pypi!
Thanks, this could be a source for confusion, I will try to include this in the README.

**Comment by johann-petrak** [comment]
README has been updated
